
package ca.ontario.health.iac.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IACCleanWSService", targetNamespace = "http://util.iac.health.ontario.ca/", wsdlLocation = "http://hscziqdcapwas01.cihs.gov.on.ca:13133/SOIACWSProjectUAT/IACCleanWSService/WEB-INF/wsdl/IACCleanWSService.wsdl")
public class IACCleanWSService
    extends Service
{

    private final static URL IACCLEANWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException IACCLEANWSSERVICE_EXCEPTION;
    private final static QName IACCLEANWSSERVICE_QNAME = new QName("http://util.iac.health.ontario.ca/", "IACCleanWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hscziqdcapwas01.cihs.gov.on.ca:13133/SOIACWSProjectUAT/IACCleanWSService/WEB-INF/wsdl/IACCleanWSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IACCLEANWSSERVICE_WSDL_LOCATION = url;
        IACCLEANWSSERVICE_EXCEPTION = e;
    }

    public IACCleanWSService() {
        super(__getWsdlLocation(), IACCLEANWSSERVICE_QNAME);
    }

    public IACCleanWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IACCLEANWSSERVICE_QNAME, features);
    }

    public IACCleanWSService(URL wsdlLocation) {
        super(wsdlLocation, IACCLEANWSSERVICE_QNAME);
    }

    public IACCleanWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IACCLEANWSSERVICE_QNAME, features);
    }

    public IACCleanWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IACCleanWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IACCleanWSDelegate
     */
    @WebEndpoint(name = "IACCleanWSPort")
    public IACCleanWSDelegate getIACCleanWSPort() {
        return super.getPort(new QName("http://util.iac.health.ontario.ca/", "IACCleanWSPort"), IACCleanWSDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IACCleanWSDelegate
     */
    @WebEndpoint(name = "IACCleanWSPort")
    public IACCleanWSDelegate getIACCleanWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://util.iac.health.ontario.ca/", "IACCleanWSPort"), IACCleanWSDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IACCLEANWSSERVICE_EXCEPTION!= null) {
            throw IACCLEANWSSERVICE_EXCEPTION;
        }
        return IACCLEANWSSERVICE_WSDL_LOCATION;
    }

}
