
package ca.ontario.health.iac.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IACCleanWSDelegate", targetNamespace = "http://util.iac.health.ontario.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IACCleanWSDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "CleanHealthNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CleanHealthNumber", targetNamespace = "http://util.iac.health.ontario.ca/", className = "ca.ontario.health.iac.util.CleanHealthNumber")
    @ResponseWrapper(localName = "CleanHealthNumberResponse", targetNamespace = "http://util.iac.health.ontario.ca/", className = "ca.ontario.health.iac.util.CleanHealthNumberResponse")
    @Action(input = "http://util.iac.health.ontario.ca/IACCleanWSDelegate/CleanHealthNumberRequest", output = "http://util.iac.health.ontario.ca/IACCleanWSDelegate/CleanHealthNumberResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://util.iac.health.ontario.ca/IACCleanWSDelegate/CleanHealthNumber/Fault/Exception")
    })
    public boolean cleanHealthNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
